name: Update User JS

on:
  schedule:
    - cron: '0 0 1 * *' # Monthly on the 1st day of the month at midnight UTC
  workflow_dispatch:
  push:
    paths:
      - 'Modifications.js'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/yokoffing/Betterfox.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories -X ours
        continue-on-error: true

      - name: Check for conflicts
        id: check_conflicts
        run: |
          if git status | grep -q 'You have unmerged paths'; then
            echo "merge_conflict=true" >> $GITHUB_OUTPUT
          else
            echo "merge_conflict=false" >> $GITHUB_OUTPUT
          fi

      - name: Handle conflicts
        if: steps.check_conflicts.outputs.merge_conflict == 'true'
        run: |
          git checkout --theirs .
          git add .
          git commit -m "Resolve conflicts by keeping our changes"

      - name: Update user.js
        run: |
          cp user.js user.js.original
          cat user.js.original Modifications.js > user.js

      - name: Commit and push changes
        run: |
          git add user.js
          git commit -m "Update user.js with latest changes and custom modifications"
          git push origin main
